### ISSUE TITLE
review post: Checkout parent branch after posting review request

### ISSUE THREAD

**Issue by OoDeLally** [salsaflow/salsaflow#104]
When i do `salsaflow review post -parent=develop`, usually I'm done working in that branch.
So It would be cool to be automatically `git checkout develop`ed when posting the review request.

But maybe some other people use a different workflow and wish to stay in the story branch?

**Comment by Argimon** [comment]
I think it’s not good idea. I can work only on one feature branch and when I post review I do not want to be switched on develop.

**Comment by iki** [comment]
Agree with @Argimon, I want to continue on the feature branch

**Comment by Bartunek** [comment]
Agree with @Argimon and @iki. 

@OoDeLally I would suggest to create some alias like `cod` or whatever as shortcut for `git checkout develop` to save some typing.

**Comment by tchap** [comment]
Yeah, an alias will probably do. Closing this.
