### ISSUE TITLE
review post: Add -pull_parent flag

### ISSUE THREAD

**Issue by pvavrik** [salsaflow/salsaflow#111]
Currently when doing `salsaflow review post --parent=develop` and the `develop` is not up to date, SF fails with:
```
[RUN]      Fetch the remote repository
[RUN]      Make sure reference 'develop' is up to date
[FAIL]     Make sure reference 'develop' is up to date
           (error = ref 'develop' is not up to date)
```

As a user I would like to have a SF parameter, e.g. `pull-parent`, which would make the cmd
`salsaflow review post --parent=develop --pull-parent` first to pull the set parent and then continued as usual.

**Comment by OoDeLally** [comment]
+1
Or a prompt
`do you want me to pull develop for you while you sip some coffee ? [Y/n]`

**Comment by tchap** [comment]
Chose to go the prompt way:

```
[RUN]      Fetch the remote repository
[RUN]      Make sure branch 'develop' is up to date

Branch 'develop' is behind 'origin/develop', and can be fast-forwarded.
Shall we perform the merge? It's all safe! [y/N]: y

[LOG]      Branch 'develop' fast-forwarded onto 'origin/develop'

Please insert the branch slug now.
```

**Comment by pvavrik** [comment]
:+1:

**Comment by tchap** [comment]
@pvavrik On the other hand, the command will still fail in case the merge is not fast-forward. Is that ok or you still want `-pull_parent` that will do merge anyway?

**Comment by pvavrik** [comment]
For me the _fast-forward only_ is just right, thanks!

**Comment by tchap** [comment]
Ok cool, so this will be released in `0.18.0` ;-)

**Comment by OoDeLally** [comment]
Yay!

**Comment by tchap** [comment]
Closing this, it will be in `0.18.0`.

**Comment by tchap** [comment]
Actually waiting for review...
