### ISSUE TITLE
Review commit df20b6f: pivotaltracker: Fix startable stories filter

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#13]
Commits to be reviewed:
- [ ] df20b6f: pivotaltracker: Fix startable stories filter

**Comment by mbernat** [comment]
@tchap why is this closed without a review?

**Comment by tchap** [comment]
@mbernat I actually discovered that it worked OK, I replaced the commit by force push, sorry. Not going to do that too often ;-)

**Comment by mbernat** [comment]
@tchap Yeah, I thought so. But please at least add a comment here next time. Thanks :)
