### ISSUE TITLE
Review post several commits at once

### ISSUE THREAD

**Issue by OoDeLally** [salsaflow/salsaflow#145]
Hello,

Right now it is possible to do

`salsaflow review post  <commitId>`

It would be nice to be able to include several commits at once

`salsaflow review post <commitId1>, <commitId2>, ...`

Thanks !

**Comment by tchap** [comment]
I can theoretically implement this, but you can already do something like `for hash in commit1 commit2 commit3; do salsaflow review post $hash; done`, right?

**Comment by tchap** [comment]
But I can take the arguments and use `git rev-list --no-walk` to parse it and then send the resulting list for code review, if that would be good enough...
