### ISSUE TITLE
Review post already-pushed commits

### ISSUE THREAD

**Issue by OoDeLally** [salsaflow/salsaflow#146]
Hello,

Sometime I push on remote `develop`, and I forget to use the `salsaflow review post` instead (I have a terrible memory).
So no review is created :cry: 

It would be nice to be able to create reviews for any commit, wherever they are.

Example:
`salsaflow review post -no_merge=true <commit1>, <commit2>, <commit3>`
with `<commit1>, <commit2>, <commit3>` being already on remote develop.

Thank you

**Comment by tchap** [comment]
It is already possible. The point is, though, to allow commit without any `Story-Id`...

**Comment by tchap** [comment]
Related to #152

**Comment by tchap** [comment]
I am closing this as dupe, please follow #152 . To support commit list is already included in #145
