### ISSUE TITLE
Review story #147: GitHub Issues: Replace `story` with `bug` or `enhancement`

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#148]
Story being reviewed: [#147](https://github.com/salsaflow/salsaflow/issues/147)

SF-Issue-Tracker: GitHub Issues
SF-Story-Key: salsaflow/salsaflow#147

The commits to be reviewed are following:
- [x] 12d4b3a: config: Improve EnsureValueFilled
- [x] e029878: issue_tracking/github: Change default labels
- [x] 554d018: issue_tracking/github: Return proper story type

----------

The content above was generated by SalsaFlow.
You can insert custom description here, but not above the separator.

**Comment by tchap** [comment]
The following commits were added to this issue:
* 554d018: issue_tracking/github: Return proper story type

**Comment by Argimon** [comment]
@tchap `implemented` label is missing for this review. Do you plan any other changes to be added to this review issue?

**Comment by tchap** [comment]
Marked as implemented and closed.
