### ISSUE TITLE
Review story SF-166: review post -include_reviewed should list also stories that are Reviewed already.

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#18]
Story being reviewed: [SF-166](https://jira.salsitasoft.com/browse/SF-166)

SF-Issue-Tracker: JIRA
SF-Story-Key: SF-166

The associated commits are following:
- [x] fd11de6: review post: Optionally list reviewed stories
- [x] 31d08ba: review post: Language corner

**Comment by tchap** [comment]
Will probably re-implement this to be able to choose interactively to list reviewed stories right in the dialog, because people might not know that they want to assign to a reviewed story. BTW I am implementing this on behalf of @iki ;-)

**Comment by mbernat** [comment]
@tchap I don't see associated commits here. Is this okay?

**Comment by tchap** [comment]
@mbernat Yeah, because Honza actually wanted to have it implemented differently, so I removed the commit from the list and reverted the change for now.

**Comment by mbernat** [comment]
@tchap can we close the issue, so that it doesn't confuse me when looking at my review queue? You can reopen it again if you ever need it later.

**Comment by tchap** [comment]
It will mess up the issue state in JIRA :-/

**Comment by mbernat** [comment]
Ok, no problem.

**Comment by tchap** [comment]
The following commits were added to this issue:
* fd11de6: review post: Optionally list reviewed stories

**Comment by tchap** [comment]
The following commits were added to this issue:
* 31d08ba: review post: Language corner
