### ISSUE TITLE
Review story SF-172: review post: Implement a dialog to offer the user to mark the stories as implemented

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#19]
Story being reviewed: [SF-172](https://jira.salsitasoft.com/browse/SF-172)

SF-Issue-Tracker: JIRA
SF-Story-Key: SF-172

The associated commits are following:
- [x] 0696767: review post: Mark the stories as implemented
- [x] 9f6f213: pivotaltracker: Fix wrong label name
- [x] 6ee2026: jira: Do nothing when story is already implemented
- [x] a008cd1: common: Add Story.State() method
- [x] 3fb4e5f: review post: Show implemented dialog when appropriate
- [x] 65bbc6f: review post: Fix panic
- [x] 9a11607: pivotaltracker: Incorporate PT client lib changes

**Comment by tchap** [comment]
The following commits were added to this issue:
* 9f6f213: pivotaltracker: Fix wrong label name

**Comment by tchap** [comment]
The following commits were added to this issue:
* 6ee2026: jira: Do nothing when story is already implemented

**Comment by tchap** [comment]
@mbernat I actually need to fix this story not to print the dialog at all when the stories are already marked as implemented, so perhaps wait with the review if you want.

**Comment by tchap** [comment]
The following commits were added to this issue:
* a008cd1: common: Add Story.State() method
* 3fb4e5f: review post: Show implemented dialog when appropriate

**Comment by tchap** [comment]
@mbernat You can review this stuff now.

**Comment by tchap** [comment]
The following commits were added to this issue:
* 65bbc6f: review post: Fix panic

**Comment by tchap** [comment]
The following commits were added to this issue:
* 6226e2a: action: Fix typo

**Comment by mbernat** [comment]
Just a note that the last commit 6226e2a disappeared from the checklist after checking it. Hopefully this was a one-time glitch.

**Comment by tchap** [comment]
The following commits were added to this issue:
* 9a11607: pivotaltracker: Incorporate PT client lib changes
