### ISSUE TITLE
Review commit 4d8694a: github/codereview: Add check into InitialiseRelease

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#29]
Commits to be reviewed:
- [x] 4d8694a: github/codereview: Add check into InitialiseRelease
- [x] 2785dc2: github/codereview: Fix wrong error check
- [x] 5e5f995: github/codereview: Change milestoneForVersion

**Comment by tchap** [comment]
The following commits were added to this issue:
* 2785dc2: github/codereview: Fix wrong error check

**Comment by mbernat** [comment]
@tchap hm, would be nice if the issue somehow indicated that no more commits are coming. It's really confusing because I don't know when to start or end reviewing otherwise.
Of course, in exceptional cases it makes sense to reopen and fix something, but that shouldn't be the rule.

**Comment by tchap** [comment]
@mbernat Found the bug now during testing, so I used `salsaflow review post -fixes`. Couldn't know in advance. You did the right thing :tm:

**Comment by mbernat** [comment]
@tchap yeah, all right. But it happened more than once that commits kept coming even after I started reviewing or that I closed the issue and I reopened it. Would be nice if GH somehow supported the IMPLEMENTED label :)

**Comment by tchap** [comment]
@mbernat True. I will write down a note.

**Comment by tchap** [comment]
The following commits were added to this issue:
* 5e5f995: github/codereview: Change milestoneForVersion
