### ISSUE TITLE
Review story SF-158: Always push on `review post` so that the commits are available in the remote.

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#4]
Story being reviewed: [SF-158](https://jira.salsitasoft.com/browse/SF-158)

SF-Issue-Tracker: JIRA
SF-Story-Key: SF-158

The associated commits are following:
- [x] 7b28d8c: review post: Always push when on branch tip
- [x] 9abb107: git: Add function comment

**Comment by tchap** [comment]
@mbernat Check this ;-)

**Comment by tchap** [comment]
Not sure why I cannot assign you to the issue. Probably because you haven't joined the org yet?

**Comment by tchap** [comment]
Now it works :-)

**Comment by mbernat** [comment]
@tchap No idea what's happening here, I've never used this stuff before :)
Should I click on the commit and raise issues there?

**Comment by tchap** [comment]
Yeah, raise issues there and use @tchap...

**Comment by tchap** [comment]
The following commits were added to this issue:
* 9abb107: git: Add function comment
