### ISSUE TITLE
Review story SF-221: Pivotal Tracker module should use Stories.Iterate() instead of List()

### ISSUE THREAD

**Issue by tchap** [salsaflow/salsaflow#61]
Story being reviewed: [SF-221](https://jira.salsitasoft.com/browse/SF-221)

SF-Issue-Tracker: JIRA
SF-Story-Key: SF-221

The commits to be reviewed are following:
- [x] 00e2bdc: pivotaltracker: Use client.Stories.Iterate
- [x] 2fb3e65: Revert "pivotaltracker: Use client.Stories.Iterate"

----------

The content above was generated by SalsaFlow.
You can insert custom description here, but not above the separator.

**Comment by tchap** [comment]
The following commits were added to this issue:
* d7c9e13: pivotaltracker: Change import path to use gopkg.in

**Comment by tchap** [comment]
The following commits were added to this issue:
* 2fb3e65: Revert "pivotaltracker: Use client.Stories.Iterate"
* 5d4302d: pivotaltracker: Change import path to use gopkg.in

**Comment by tchap** [comment]
@mbernat Force pushed new commits, make sure you are reviewing the right ones.

**Comment by tchap** [comment]
Also removed a commit from the list, it was not needed to review it.

**Comment by mbernat** [comment]
So which ones are "the right ones"?

**Comment by tchap** [comment]
Always the ones in the main list. I usually try to delete the comments that should not be here as well.
